<Project>

  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Arnaud Leclerc</Authors>
    <RepositoryUrl>https://github.com/arnaudleclerc/AzureMapsControl.Components</RepositoryUrl>
    <RepositoryType>GIT</RepositoryType>
  </PropertyGroup>

</Project>
