namespace AzureMapsControl.Components.Logger
{
    using Microsoft.Extensions.Logging;

    internal enum AzureMapLogEvent
    {
        AzureMap_OnInitialized = 1000,
        AzureMap_OnAfterRenderAsync = 1001,
        AzureMap_AttachDataSourcesCallback = 1002,
        AzureMap_DrawingToolbarEvent = 1003,
        AzureMap_HtmlMarkerEventReceivedAsync = 1004,
        AzureMap_LayerEventReceivedAsync = 1005,
        AzureMap_MapEventReceivedAsync = 1006,
        AzureMap_ClearMapAsync = 1007,
        AzureMap_PopupEventReceivedAsync = 1008,
        AzureMap_DataSourceEventReceivedAsync = 1009,
        MapService_AddMapAsync = 2000,
        AnimationService_Snakeline = 3000,
        AnimationService_MoveAlongPath = 3001,
        AnimationService_FlowingDashedLine = 3002,
        AnimationService_DropMarkers = 3003,
        AnimationService_GroupAnimations = 3004,
        AnimationService_Drop = 3005,
        AnimationService_SetCoordinates = 3006,
        AnimationService_Morph = 3007,
        AnimationService_MoveAlongRoute = 3008,
        Map_AddControlsAsync = 4000,
        Map_AddSourceAsync = 4001,
        Map_RemoveSourceAsync = 4002,
        Map_ClearSourcesAsync = 4003,
        Map_AddDrawingToolbarAsync = 4004,
        Map_UpdateDrawingToolbarAsync = 4005,
        Map_RemoveDrawingToolbarAsync = 4006,
        Map_AddHtmlMarkersAsync = 4007,
        Map_UpdateHtmlMarkersAsync = 4008,
        Map_RemoveHtmlMarkersAsync = 4009,
        Map_ClearHtmlMarkersAsync = 4010,
        Map_AddLayerAsync = 4011,
        Map_RemoveLayersAsync = 4012,
        Map_ClearLayersAsync = 4013,
        Map_SetCameraOptionsAsync = 4014,
        Map_SetStyleOptionsAsync = 4015,
        Map_SetUserInteractionAsync = 4016,
        Map_SetTrafficAsync = 4017,
        Map_AddPopupAsync = 4018,
        Map_ClearPopupsAsync = 4019,
        Map_CreateImageFromTemplate = 4020,
        Map_SetCanvasStylePropertyAsync = 4021,
        Map_SetCanvasStylePropertiesAsync = 4022,
        Map_SetCanvasContainerStylePropertyAsync = 4023,
        Map_SetCanvasContainerStylePropertiesAsync = 4024,
        Map_GetCameraOptionsAsync = 4025,
        Map_GetStyleOptionsAsync = 4026,
        Map_GetTrafficOptionsAsync = 4026,
        Map_GetUserInteractionOptionsAsync = 4027,
        OverviewMapControl_UpdateAsync = 5000,
        OverviewMapControl_SetOptionsAsync = 5001,
        Popup_OpenAsync = 6000,
        Popup_CloseAsync = 6001,
        Popup_RemoveAsync = 6002,
        Popup_UpdateAsync = 6003,
        Popup_SetOptionsAsync = 6004,
        Popup_ApplyTemplateAsync = 6005,
        Source_AddAsync = 7000,
        Source_RemoveAsync = 7001,
        Source_ImportDataFromUrlAsync = 7002,
        Source_ClearAsync = 7003,
        Source_DisposeAsync = 7004,
        Source_GetOptionsAsync = 7005,
        Source_SetOptionsAsync = 7006,
        DataSource_GetShapesAsync = 7100,
        HtmlMarker_TogglePopupAsync = 8000,
        GeolocationControl_GetLastKnownPositionAsync = 9000,
        GeolocationControl_DisposeAsync = 9001,
        GeolocationControl_SetOptionsAsync = 9002,
        GeolocationControl_AddEventsAsync = 9003,
        GeolocationService_IsGeolocationSupportedAsync = 9100,
        FullScreenService_IsFullScreenSupportedAsync = 10000,
        FullScreenControl_DisposeAsync = 10100,
        FullScreenControl_SetOptionsAsync = 10101,
        FullScreenControl_IsFullScreenAsync = 10102,
        FullScreenControl_AddEventsAsync = 10103,
        IndoorService_CreateIndoorManagerAsync = 11000,
        IndoorManager_InitializeAsync = 11100,
        IndoorManager_DisposeAsync = 11101,
        IndoorManager_GetCurrentFacilityAsync = 11102,
        IndoorManager_GetOptionsAsync = 11103,
        IndoorManager_GetStyleDefinitionAsync = 11104,
        IndoorManager_SetDynamicStylingAsync = 11105,
        IndoorManager_SetFacilityAsync = 11106,
        IndoorManager_SetOptionsAsync = 11107,
    }

    internal static class Extensions
    {
        internal static void LogAzureMapsControlTrace(this ILogger logger, AzureMapLogEvent logEvent, string message, params object[] args) => logger.LogAzureMapsControl(LogLevel.Trace, logEvent, message, args);
        internal static void LogAzureMapsControlDebug(this ILogger logger, AzureMapLogEvent logEvent, string message, params object[] args) => logger.LogAzureMapsControl(LogLevel.Debug, logEvent, message, args);
        internal static void LogAzureMapsControlInfo(this ILogger logger, AzureMapLogEvent logEvent, string message, params object[] args) => logger.LogAzureMapsControl(LogLevel.Information, logEvent, message, args);
        internal static void LogAzureMapsControl(this ILogger logger, LogLevel logLevel, AzureMapLogEvent logEvent, string message, params object[] args) => logger.Log(logLevel, new EventId((int)logEvent), message, args);
    }
}
