name: code-coverage

on:
  push:
    branches:
      - releases/**
      - develop
      - main
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: 
      - develop
      - main
    paths:
      - src/**
      - tests/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj
    - name: Test
      run: dotnet test ./tests/AzureMapsControl.Components.Tests/AzureMapsControl.Components.Tests.csproj --collect:"XPlat Code Coverage" -r ./tests/AzureMapsControl.Components.Tests/testresults
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./tests/AzureMapsControl.Components.Tests/testresults
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)